import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import type { PutObjectInput, StorageBackend } from './types.js';

/**
 * Writes artifact content under a local directory - dev/host-mode only.
 * `getUrl` returns a relative path under apps/server's `/artifacts/*` proxy
 * route rather than a `file://` URL, since the browser needs an HTTP URL
 * either way; the proxy route reads the same file back via `get()`.
 */
export class LocalFsStorage implements StorageBackend {
  constructor(private readonly baseDir: string) {}

  private resolvePath(key: string): string {
    // `key` is always generated by this package (see ../service.ts) as a
    // ULID-prefixed slug, never taken verbatim from user/agent input, so a
    // plain join is safe - no path traversal surface to defend against here.
    return path.join(this.baseDir, key);
  }

  async put(input: PutObjectInput): Promise<void> {
    const filePath = this.resolvePath(input.key);
    await mkdir(path.dirname(filePath), { recursive: true });
    await writeFile(filePath, input.body);
  }

  async get(key: string): Promise<Buffer> {
    return readFile(this.resolvePath(key));
  }

  async getUrl(key: string): Promise<string> {
    return `/artifacts/raw/${encodeURIComponent(key)}`;
  }

  async delete(key: string): Promise<void> {
    await rm(this.resolvePath(key), { force: true });
  }
}
